name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up rbenv
        run: |
          echo "$HOME/.rbenv/shims" >> $GITHUB_PATH
          echo "$HOME/.rbenv/bin" >> $GITHUB_PATH

      - name: Run CI
        env:
          RAILS_ENV: test
        run: bin/ci

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore

